services:

    nginx:
        image: nginx:latest
        ports:
        - "443:443"
        volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./wordpress.local.pem:/etc/ssl/certs/wordpress.local.pem
        - ./wordpress.local-key.pem:/etc/ssl/private/wordpress.local-key.pem
        depends_on:
        - wordpress

    db:
        image: mariadb:latest
        volumes:
            - ./db_data:/var/lib/mysql
        ports:
            - 4306:3306
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=xxxxxxxx
            - MYSQL_DATABASE=mkmdb
            - MYSQL_USER=elar
            - MYSQL_PASSWORD=xxxxxxxx
    wordpress:
        image: wordpress:latest
        depends_on:
            - db
        volumes:
            - ./wp_data:/var/www/html
        restart: always
        environment:
            - WORDPRESS_DB_USER=elar
            - WORDPRESS_DB_PASSWORD=xxxxxxxx
            - WORDPRESS_DB_HOST=db
            - WORDPRESS_DB_NAME=mkmdb

volumes:
  db_data: {}
  wp_data: {}
